apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifact
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 2104011/docker101:0.2
        ports:
        - containerPort: 80